BlueConduit/open-data-platform

client/public/index.html, client/src/assets/styles/global.scss, client/src/components/MapLegend.vue, client/src/components/MapPopupContent.vue, client/src/components/MapView.vue
Addresses: [Create responsive map with conditional styling](https://app.shortcut.com/blueconduit/story/4854/create-responsive-map-with-conditional-styling)
- Adds conditional styling to map based on population served of violations_by_county data.
- Adds MapLegend component, which is displaying population served data.
- Adds MapPopupContent component, which is displaying Lead & Copper rule data.
- Conditional styling, Mapbox click handler, MapLegend vue component, MapPopupContent component.
- Data displayed on map.
N/A
npm run serve to display the map. Click on any territory to view popup.
[link](https://www.figma.com/file/GMmbr571gwxeeAYI0wKzG3/Nationwide-map?node-id=198%3A286)
=> Conditional styling

cdk/src/open-data-platform/data-plane/data-plane-stack.ts
=> Add back rootSchema declaration in data plane.

cdk/package-lock.json, cdk/package.json, cdk/src/open-data-platform/data-plane/schema.sql, cdk/src/open-data-platform/lambda/data-import-stack.ts, cdk/src/open-data-platform/lambda/write-demographic-data.handler.ts
For Brett to work off of while I'm OOO 
This starts to get geometries into the DB
=> Lead prediction lambda

client/src/components/MapView.vue
Addresses: [a-user-can-search-for-an-address-in-a-searchbar](https://app.shortcut.com/blueconduit/story/5176/a-user-can-search-for-an-address-in-a-searchbar)
Add navigation controls (zoom in / out).
- Navigation control on map.
N/A
N/A
npm run serve
=> Add navigation control (zoom in / out) to map.

cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts, cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data-handler.handler.ts, cdk/src/open-data-platform/data-plane/schema/schema.handler.ts, cdk/src/open-data-platform/data-plane/schema/schema.sql
This is a commit that didn't make it into https://github.com/BlueConduit/open-data-platform/pull/43. I'm unsure what happened it,  but it includes the responses to the last wave of feedback.
=> Uncommited changes from Pull 43

cdk/src/open-data-platform/data-plane/schema/schema.sql
- Adds state + county geo ID columns to the water_systems and violations tables 
- Creates function sources to fetch lead connections (water systems) and violations data either aggregated by state, or by water system depending on zoom level.
**Note**:
1. This does **not** include code to populate those columns in the lambdas yet. This is because we are awaiting updated files from Jared which should make this population straightforward (as opposed to what I did for testing, which was a more complicated join statement).
2. This adds these columns via the initial create statement (as opposed to an alter table statement). This is to keep the file clean and concise while the …
=> Add aggregation columns

cdk/src/open-data-platform/data-plane/schema/schema.sql, client/src/components/MapView.vue, client/src/data_layer_configs/lead_and_copper_violations_by_water_system_config.ts
Switch violations tile source to violations_function_source.
Note: Legend was not modified. Instead left a TODO since Justine is working on setting that up separately. 
- N/A
- Violations config to switch tile source
- schema.sql to cast sum to int (was previously coming through as string for some reason) and to switch the zoom toggling to 4 instead of 6 to align with the function Justine added (this looks better in UI).
-N/A
npm run serve -> violations layer
https://screenshot.googleplex.com/9B4N8UmZESumqpZ
https://screenshot.googleplex.com/XkWyHvX7bSUWxKH
=> Violations function source

cdk/src/open-data-platform/data-plane/schema/schema.sql
Add precomputed tables at state, county, zip level for lead_connections (water_systems table). Modify lead_connections_function_source to point to this state table.
- Table defs + inserts
- Lead connections function source
- N/A
run schema.sql, run npm run serve to view data in FE
=> Lead connections agg tables

cdk/src/open-data-platform/data-plane/api/api-stack.ts, client/src/components/MapContentContainer.vue, client/src/components/MapGeocoderWrapper.vue, client/src/components/MapView.vue, client/src/components/NavigationBar.vue, client/src/components/PredictionPanel.vue, client/src/main.ts, client/src/router.ts, package-lock.json
Addresses: Implement API calls to use url params (lat/long) to fetch scorecard data C1_FR2
Adds search bar that calls /geolocate/latlng based on input and console.log()s the output. This only happens on "/" not "/map". The next PR will update the app state with the lat long and move the API request out of the geocoder
- The style we were using was broken in mapbox studio so I'm using another for now
Searched my zipcode and it returns the API response
=> Call /geolocate/latlng when user searches zipcode 

api/src/watersystem/get.handler.ts, api/src/zipcode/scorecard/get.handler.ts, cdk/src/open-data-platform/data-plane/api/api-stack.ts, cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts, cdk/src/open-data-platform/data-plane/data-import/utils/lambda-function-factory.ts
Addresses: API skeleton (AWS api gateway + lambda creation). Specifically /watersystem/{pws_id} and /zipcode/scorecard/{zip_code}
/get handlers for both water system and zipcode/scorecard
AWS console gateway test events
=> /watersystem/{pws_id} and /zipcode/scorecard/{zip_code}

api/src/zipcode/scorecard/get.handler.ts, cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data.handler.ts, cdk/src/open-data-platform/data-plane/model/water-systems-table.ts, cdk/src/open-data-platform/data-plane/schema/schema.sql
Add tables to hold scorecard data.  
See: https://docs.google.com/spreadsheets/d/1aJV4BP5NyZM7Hrp682AMQbD9IEzt0JmzNVcVczf4Zj0
- Tables for lead predictions and U.S. demographic data needed for scorecard
- schema.sql
- N/A
paste new code into query editor
=> Add initial tables needed for scorecard. Posting for testing on laptop.

client/src/components/NationwideMap.vue
Listen on lat/long change in the map and zoom to new coordinates any change in lat/long.
Screencast: https://watch.screencastify.com/v/vTZFxuZqJueO1EMrW2nY
=> Fix geocoder zoom to search location.

cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts, cdk/src/open-data-platform/data-plane/data-import/write-aggregate-county-demographic-data.handler.ts, cdk/src/open-data-platform/data-plane/data-import/write-aggregate-state-demographic-data.handler.ts, cdk/src/open-data-platform/data-plane/model/aggregate_us_demographic_table.ts
Add lambdas to insert county and state demographic data to aggregate_us_demographics table.
Deploy + run handlers!
=> Create lambdas for inserting county + state demographics

cdk/src/open-data-platform/data-plane/schema/schema.sql
Add back state and county demographics tables which pull from demographics table (not related to aggregate_us_demographics). These were removed in https://github.com/BlueConduit/open-data-platform/pull/73/files. This is still being used for the map, however we may switch to showing the aggregate_us_demographic data there in the future.
Ran schema.sql
=> Add back state/county aggregate demographics 

cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data.handler.ts, cdk/src/open-data-platform/data-plane/schema/schema.sql
Populate state_census_geo_id on water_systems table in lambda. I'll do violations separately after the refactor is submitted.
=> Add population of state census geo id to water_systems handler.

client/src/api/api_client.ts, client/src/assets/messages/scorecard_messages.ts, client/src/assets/styles/global.scss, client/src/components/ActionSection.vue, client/src/components/PredictionPanel.vue, client/src/components/ScorecardSummaryPanel.vue, client/src/components/ScorecardSummaryRow.vue, client/src/components/landing_page/FilterInfoSection.vue, client/src/components/landing_page/ResourcesSection.vue, client/src/views/ScorecardView.vue
Addresses: Finalize scorecard content + styling
Updates some styling on the scorecard page to closer align with other pages. 
Contextualizes numbers in scorecard factors for now. These numbers will be run through UXR testing to determine whether we should show them at all. 
Formats the demographic numbers to text rather than raw numbers. See screenshot.
=> Update raw values for scorecard summary factors

client/src/assets/styles/global.scss, client/src/views/AboutUsView.vue
Changes button hover / disabled color and makes change to about us change text alignment.
=> tiny styling changes

cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data.handler.ts
Update write-water-systems-handler to use lead_connections_count instead of lead_connections
=> Update write-water-systems-handler to use lead_connections_count

cdk/src/open-data-platform/frontend/frontend-stack.ts
Addresses: [CORS issue](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/8Mf1mSskOS3bwrwmGqhOq-)
During local development, devs open a client at `localhost` that makes requests to a tilesever in their sandbox environment. Previously, CORS policy (occasionally) blocked these requests due to it being from a different origin.
This PR allows all origins in sandbox.
=> Allow all origins in sandbox.

client/src/App.vue, client/src/components/MapGeocoderWrapper.vue, client/src/components/NationwideMap.vue, client/src/components/PredictionPanel.vue, client/src/components/SearchBar.vue, client/src/model/slices/demographic_data_slice.ts, client/src/model/slices/geo_data_slice.ts, client/src/model/slices/lead_data_slice.ts, client/src/router.ts
Adds lat/long to URL from search on scorecard page and clears state between pages. Also removes duplicate marker.
- A few reducers to clear the state when a user switches pages.
ran locally, searched different results from the scorecard, and toggled between pages.
=> Scorecard search

client/src/components/NationwideMap.vue, client/src/components/PredictionPanel.vue
Fixes clear search bug (would zoom to 0,0) and adds call to fetch water system data for addresses (previously only fetched parcel data)
ran locally, searched for parcel without data, cleared search
=> Fix zoom out

cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data.handler.ts
Addresses: [Complete low-hanging-fruit DB optimizations for tile serving](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/blYIQsdPnww7YU8xsoy_aD)
- '[Clustering](https://www.postgresql.org/docs/current/sql-cluster.html)' physically sorts the bytes on disk in a table
- The effect of this is that reading data from an index sequentially becomes faster because you need fewer disk seeks
- In our case (serving tiles), the polygons for each tile are by-definition close to each other, since they're on the same tile, making this a no-brainer
- The effect of this is that a slow tile fetch (e.g., z, x, y, = 6, 14, 25) gets 10-20% faster.
- Including the bbox index:
- Exec time before: 1103ms, 1139ms, 1130ms
- Exec time after: 838ms, 930ms, 831ms
- This PR updates the water_systems …
=> Cluster water_systems data by its spatial index

client/src/components/NationwideMap.vue, client/src/views/ScorecardView.vue
Addresses: [Insert link to Shortcut story]()
Does not create popup when on the scorecard page. 
In UI
=> Remove popup

client/package-lock.json, client/src/components/MapGeocoderWrapper.vue, client/src/components/MapPopupContent.vue, client/src/components/NationwideMap.vue, client/src/components/SearchBar.vue, client/src/model/slices/map_data_slice.ts, client/src/views/ScorecardView.vue
Addresses: 
- Searching on Population / Violations data layers takes you back to water systems layer when zooming to a result
- Bug where you have to click twice on data layer to see a layer change on nationwide map
Tested locally + in sandbox: https://kailajeter.leadout-sandbox.blueconduit.com/
Clicked around nationwide map, switched layers when zoomed into address, searched new address in violations layer.
=> Small UI fixes

client/src/assets/messages/landing.ts, client/src/assets/styles/global.scss, client/src/components/landing_page/SearchSection.vue
Addresses: [Update site copy](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/8IIYSi8ScWH7-DqywD4Otv)
This implements the suggested changes in [this doc](https://docs.google.com/document/d/1Dk5Y1--Uh8OheDdpA2phT2x9nDe464iRcUvCb_nepW8/edit#).
- Most text.
- Added a 50% black filter over the hero image for text readability ([context](https://lslr.slack.com/archives/C03CCS92TC5/p1663362388416319)).
- Narrowed header spacing 
Test in my sandbox: https://beekley.leadout-sandbox.blueconduit.com/
=> Update copy for landing page

client/src/components/landing_page/SearchSection.vue
Reduce spacing of landing page so that the top section fits on screen
=> Reduce spacing of landing page so that the top section fits on screen

.github/workflows/unit-test.yaml
We now have client tests, so let's block merging if they don't pass
- Adds the client test to the github workflow that runs when a PR is created.
[It passes!](https://github.com/BlueConduit/open-data-platform/actions/runs/3114299609/jobs/5049980553)
=> Test client on PR creation

cdk/src/open-data-platform/data-plane/schema/schema.sql
Addresses: [Fix tileserver function source](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/apv7QsIhjTr4ZTdhpDZ4lS)
- We should be casting polygons to `::geography` types for area calculations.
- See [here](http://postgis.net/workshops/postgis-intro/geography.html) for detailed explanation for why. 
- I'd failed to do this in schema.sql
- But this didn't affect prod and dev because I'd given folks the correct commands to run to manually fix it.
- This fix is live in production now. Nobody needs to do anything.
- If we need to make the same fix anywhere else, use the following:
```sql
UPDATE public.water_systems
SET approx_area_sq_km = ST_Area(ST_Transform(geom, 4326)::geography) / 1000000;
```
- N/A
- Area calculations now use a ::geography type so they return a …
=> Use geography types for area calculations

client/src/components/SearchBar.vue
Remove pills from map and make dropdown update URL so that it actually changes the current data layer.
=> Fix map dropdown

cdk/src/monitoring/monitoring-stack.ts
Got a [notification](https://lslr.slack.com/archives/C0406KX4DPC/p1664406984942709) that canaries were failing in the Deployments env. LeadOut does not run in the Deployments env. So this PR removes the canaries from there (while keeping the monitoring for the pipeline in general).
=> Remove canary from Deployments env.

README.md, docs/data-import.md
Add README for data import instructions: https://docs.google.com/document/d/1r_LgkAefBuWApC-BqmBw4_4oKdZoXsYQooO0MAz7elg/edit#
=> Add data import doc

cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts
Set end_date to null if it is empty. Without this the TO_DATE function returns a default date.
=> Violations null date

client/src/components/resources_page/FilterInfoSection.vue, client/src/components/resources_page/FilterTypesSection.vue, client/src/components/resources_page/RecommendationsSection.vue
Add center-container class to resources page section to recenter content.
=> Fix resources

client/src/assets/styles/global.scss, client/src/components/landing_page/ExploreMapSection.vue, client/src/components/scorecard_page/ContactCitySection.vue
Add back lighter gold and change sections that had this color originally.
=> Add back lighter gold.

README.md, cdk/src/pipeline/pipeline-stack.ts, docs/release-process.md
There are a few things I want to do with the release process but don't think I'll have time for. I want to write them down, so people know they aren't implemented yet, and maybe could implement them later.
- Release docs ([rendered here](https://github.com/BlueConduit/open-data-platform/blob/docs/release2/docs/release-process.md))
=> Add release process docs

client/src/assets/blog/lead_health_effects.ts, client/src/router.ts
screenshot: https://screenshot.googleplex.com/3WnxVZ9vraiEAAM
content from: https://docs.google.com/document/d/1GJ6M1ioF0Nwy139qnz7yZw6L_Nl5TdEkUO4D3ztpwUE/edit#
Not yet linked anywhere.
=> Add 'How Lead Exposure Affects Your Health' blog post

client/src/components/NationwideMap.vue, client/src/components/SearchBar.vue, client/src/components/resources_page/FilterTypesSection.vue
Hide legend and 'View by' label in searchbar in mobile.
Screenshot: https://screenshot.googleplex.com/5cKXDqE5BYhe7E6
=> Mobile map styling changes

client/src/assets/messages/landing.ts
Change thank you message to PM ask.
=> Thank you message change

client/src/components/landing_page/UnderstandingLslSection.vue, client/src/views/ScorecardView.vue
Update some CTAs on landing page and scorecard.
=> Update CTA links

cdk/src/open-data-platform/frontend/frontend-stack.ts
This reverts commit 6c176cdd2f4a271f3ddc782e1f6672b6fe7e3390.
The intent is to make staging briefly accessible by letting this commit deploy through staging CodePipeline.
The original commit will be restored shortly.
Addresses: [Insert link to Shortcut story]()
_Short, descriptive summary of the changes_
_Add descriptions, steps, or checklists for how someone can review this PR to verify it's working as intended_
=> Temporarily Revert "network: top level redirect to blueconduit.com/lsl-solutions/nationwide-map/ (#233)"

cdk/src/open-data-platform/frontend/frontend-stack.ts
This reverts commit a233e2c72dee6cc05c0b796d9983eeee52423ec0, reinstating the top level redirect we originally deployed.
Addresses: [Insert link to Shortcut story]()
_Short, descriptive summary of the changes_
_Add descriptions, steps, or checklists for how someone can review this PR to verify it's working as intended_
=> Revert (#234); Reinstate "network: top level redirect to blueconduit.com/lsl-solutions/nationwide-map/ (#233)"

cdk/src/open-data-platform/frontend/frontend-stack.ts, cdk/src/open-data-platform/network/dns.ts
Addresses: [Insert link to Shortcut story]()
_Short, descriptive summary of the changes_
_Add descriptions, steps, or checklists for how someone can review this PR to verify it's working as intended_
=> wip: add duplicate route to leadout app

client-new/src/assets/styles/base/button.scss, client-new/src/assets/styles/base/properties.scss, client-new/src/assets/styles/main.scss, client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue
Addresses: [Story 8077](https://app.shortcut.com/blueconduit/story/8077/leadout-ui-internal-testing-scorecard)
- Added small style changes for the buttons, links.
- Updated formatting of data passed to the MapPanel component.
=> Fixes for Story 8077

client-new/src/assets/styles/main.scss, client-new/src/components/GeocodeControl.vue, client-new/src/components/InfoCard.vue, client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue
Addresses: [Story 8072](8072), [Story 8077](8077)
Implemented search functionality, UI and interaction adjustments.
=> Layer updates for 8072, 8077

client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue
Updated the water service layer path and added the tier data to the map panel component.
=> Updated water service layer

client-new/src/components/MapSection.vue
Updated the fields used to determine the layer fill colors.
=> Updated layer color fields

client-new/src/assets/styles/base/popup.scss, client-new/src/assets/styles/main.scss, client-new/src/components/HelpModal.vue, client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue
Addresses: [8072](https://app.shortcut.com/blueconduit/story/8072/leadout-ui-internal-testing-map-layers-and-components)
- Fix for map panel toggle when activating the PWS layer
- Updated basemap layer
- Start of refactoring layer queries to enable bypassing API limits
- Style adjustments
=> UX updates

client-new/src/assets/styles/base/button.scss, client-new/src/assets/styles/base/input.scss, client-new/src/assets/styles/base/tooltip.scss, client-new/src/assets/styles/main.scss, client-new/src/components/GeocodeControl.vue, client-new/src/components/HelpModal.vue, client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue, client-new/src/components/SearchMobile.vue
Addresses: [8072](https://app.shortcut.com/blueconduit/story/8072/leadout-ui-internal-testing-map-layers-and-components),[8077](https://app.shortcut.com/blueconduit/story/8077/leadout-ui-internal-testing-scorecard), [8465]https://app.shortcut.com/blueconduit/story/8465/leadout-ui-internal-testing-mobile-adjustments),
Added hover tooltips, secondary button for map panel, mobile search component
=> Ux UI updates

client-new/src/assets/styles/base/button.scss, client-new/src/components/GeocodeControl.vue, client-new/src/components/HelpModal.vue, client-new/src/components/InfoCard.vue, client-new/src/components/Loading.vue, client-new/src/components/MapLegend.vue, client-new/src/components/MapPanel.vue, client-new/src/components/MapSection.vue, client-new/src/components/SearchMobile.vue
Addresses: [8856](https://app.shortcut.com/blueconduit/story/8856/loading-icon), [8746](https://app.shortcut.com/blueconduit/story/8746/new-query-zoom-layer-related-asks-april-14-2023), [8465](https://app.shortcut.com/blueconduit/story/8465/leadout-ui-internal-testing-mobile-adjustments)
Updated mobile components, added new loading icon, fixes for zoom query issues, and reset button functionality.
=> Mobile Components, UX fixes
