BlueConduit/open-data-platform

client/package-lock.json
client/package.json
client/src/components/MapView.vue

Addresses: [The map frontend displays a shape that is stored in the DB](https://app.shortcut.com/blueconduit/story/4759/the-map-frontend-displays-a-shape-that-is-stored-in-the-db?cf_workflow=500000067&ct_workflow=all&vc_group_by=day)
Calls API to get s3 bucket URL of water boundary geojson file and displays this in the FE. This does not yet involve the DB.
Axios dependencies [link to documentation](https://axios-http.com/docs/intro). We can discuss whether this is the way we want to keep going but seems like this + native API support is all and this seems more robust.
Source of data from static s3 bucket URL --> an API call. Additionally fixes map styling so that data renders. 
Run npm run serve to view changes. Warning that the data takes a few seconds to render.

Dummy data

---

cdk/package-lock.json
cdk/package.json
cdk/src/open-data-platform/data-plane/data-plane-stack.ts
cdk/src/open-data-platform/lambda/data-import-stack.ts
cdk/src/open-data-platform/lambda/write-demographic-data-handler.ts
cdk/src/open-data-platform/lambda/write-demographic-data.handler.ts

Addresses: [https://app.shortcut.com/blueconduit/story/4867/serve-static-census-data-from-postgresql-db-in-aws](Shortcut)
Use databases/pg to write to db instead of AWS's RDS service. Has bulkInsert and helpful formatting helpers. 
Using manual test events inside the lambda function. Will follow-up with Gateway call

Use databases/pg to insert and delete rows instead of RDS service

---

cdk/src/open-data-platform/frontend/frontend-stack.ts

Addresses: n/a
Previously, the function had a common name that each environment would use. This caused `cdk deploy` to fail. So it now has a unique name.
- n/a
- Changed function name.
- n/a
cdk deploy works and [my function has my own name on it](https://us-east-1.console.aws.amazon.com/cloudfront/v3/home?region=us-east-2#/functions/beekley-OpenDataPlatformFrontend-tileServerPrefixTrim).

Give cloudfront function a unique name.

---

cdk/src/open-data-platform/data-plane/schema/schema.sql
cdk/src/resource-initializer.ts

Addresses: [Parcel level data in DB](https://app.shortcut.com/blueconduit/story/5146/parcel-level-lsl-prediction-data-for-one-city-is-stored-in-the-db)
Just the table. The lambda that imports data here will come once we have that data. I'm trying to keep PRs short.
- `parcels` table.
- Removed the constants, since they weren't working anyway. SQL doesn't let you define constants like that unless it's in a transaction or something.
- Section header comments looks different. I'm not set on this, but wanted to make them stand out more.
- n/a
n/a

Create parcel-level data table.

---

client/src/components/MapView.vue

Addresses: [a-user-can-use-their-device-s-location-to-search-on-the-map](https://app.shortcut.com/blueconduit/story/5158/a-user-can-use-their-device-s-location-to-search-on-the-map)
Adds Geolocate control to map which allows user to zoom to their current location.
- Geolocate control on map
- MapView
N/A
npm run serve
https://watch.screencastify.com/v/bQsadTt5gpDQHtJzMlab

Add geolocate control to map.

---

cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data-handler.handler.ts

Addresses: [Display Water System data on the map](https://app.shortcut.com/blueconduit/story/4784/display-water-system-data-on-the-map)
NaN values are in the geoJson file we are parsing. We need to convert this to 0 so that the mapbox library does not throw an error and return black squares

Turn NaN values to 0 so that map does not show black

---

client/src/data_layer_configs/water_systems_config.ts

The former gave me [this error](https://stackoverflow.com/questions/33507566/mixed-content-blocked-when-running-an-http-ajax-operation-in-an-https-page) when deployed.
npm run serve / deploy FE.

Change http -> https in tiles URL. 

---

cdk/package-lock.json
cdk/package.json
cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts
cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts
cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data-handler.handler.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [Display EPA violations data on the map](https://app.shortcut.com/blueconduit/story/5481/display-epa-violations-data-on-the-map)
Adds the writeViolationsDataFunction which reads from a static file in s3 and writes to the epa_violations table. 
This information is only available at the water system level, so we may want to consider moving it to water systems eventually but I think for now keeping this separate it best for simplicity. 
Data handler for the lambda function 
Schema.sql creates the epa_violations table if it does not exist. 
Test events in AWS console

Add lambda handler to write into epa_violations table 

---

cdk/package-lock.json
cdk/package.json
cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts
cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts
cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data-handler.handler.ts
cdk/src/open-data-platform/data-plane/schema/schema.handler.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql
cdk/tsconfig.json

Fix water systems and epa violations handlers to write all rows
Addresses: [Display EPA violations data on the map](https://app.shortcut.com/blueconduit/story/5481/display-epa-violations-data-on-the-map)
Updates both water systems and violations data handlers to use a new better-supported library for writing to the db (pg not @databases/pg).
Allows passing in start index for writing rows to make it easier to run this lambda multiple times without too much editing.
With both handlers fixed, I could create a violations_count view that aggregated violations at the water system level. 
New view inside schema.sql
Both handlers have been updated and refactored. 
Use of @database/pg
AWS test events

Fix water systems and epa violations handlers to write all rows

---

cdk/package-lock.json
cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts
cdk/src/open-data-platform/data-plane/data-import/write-demographic-data.handler.ts
cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [census-block-data-is-stored-in-the-db](https://app.shortcut.com/blueconduit/story/4764/census-block-data-is-stored-in-the-db)
User RDS API in demographic handler, modify demographics schema, and use broken up files.
- Name field in schema
- Insert logic (uses RDS API now)
- Schema (now stores population counts instead of derived percentages)
- N/A
deploy data plane stack and run demographic handler

Demographic data handler

---

cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts
cdk/src/open-data-platform/data-plane/data-import/write-parcels-data.handler.ts
cdk/src/open-data-platform/data-plane/model/parcel_table.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [Display parcel level LSL prediction data on the map](https://app.shortcut.com/blueconduit/story/5150/display-parcel-level-lsl-prediction-data-on-the-map)
Adds parcel data (and lead prediction data) to parcels table for city of Toledo. This writes all 140,000 rows in 1 run
Parcels lambda handler that takes parcels/toledo_parcel_preds.geojson and creates rows for db 
Schema.sql to remove some columns / rename others for consistency. 
Test events in Amazon AWS console

Add toledo parcel data to parcels table

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

Fix SQL issues with epa_violations. This includes:
- Remove FK on water systems, at least until all water systems are included in that table.
- Remove nonnull constraint on end_date since this can be null for ongoing violations.

Fix issues with epa_violations table.

---

cdk/src/open-data-platform/data-plane/data-import/write-demographic-data.handler.ts
cdk/src/open-data-platform/data-plane/model/demographic-table.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql

Add state and county geo id to the demographics table. We need this in order to do joins with state and county tables. Geometric spatial joins are too slow for our purposes. 
The table needs to be dropped and reloaded to make all the aggregations work. Aggregations will require these foreign keys be populated.
State and county geo ids added to demographics table. 
Reloaded entire demographics table with new columns

Add state and county columns to demographics

---

cdk/cdk.context.json
cdk/src/open-data-platform/network/network-stack.ts
cdk/src/pipeline/pipeline-stack.ts
cdk/src/util.ts

The lookup by tag was returning some other VPC that I couldn't actually find in our AWS account. So this hardcodes the real VPC so it's unambiguous.

Hardcode VPC id to force correct lookup.

---

cdk/cdk.context.json

This file is autogenerated when the CDK code runs and has to make a call to AWS (such as during the VPC lookup I recently added). However, it still had the weird old VPC from the first version of that code. So this PR removes it.

Remove VPC artifact from previous code.

---

cdk/src/open-data-platform/data-plane/schema/schema.sql
client/src/App.vue
client/src/components/MapPopupContent.vue
client/src/components/MapView.vue
client/src/components/SearchBar.vue
client/src/data_layer_configs/lead_and_copper_violations_by_water_system_config.ts
client/src/data_layer_configs/lead_service_lines_by_parcel_config.ts
client/src/data_layer_configs/lead_service_lines_by_water_systems_config.ts
client/src/data_layer_configs/population_by_census_block_config.ts
client/src/model/data_layer.ts

Addresses: 
- [Display parcel level LSL prediction data for Toledo on the map](https://app.shortcut.com/blueconduit/story/5150/display-parcel-level-lsl-prediction-data-for-toledo-on-the-map)
- [Complete data transformation](https://app.shortcut.com/blueconduit/story/5678/complete-data-transformation)
Switches lead connections data layer to point to:
- Lead connections function source for zoom < 12 (zoomed further out). This provides aggregation over state level when zoom < 6.
- Parcels when zoom > 12 (zoomed far in). 
Modifies popups + legends accordingly.
- Data layer for parcels data. 
- Zoom listener which toggles source of lead connections layer between water systems data + parcel data. This visual layer is not selectable in the search bar. 
- N/A
run with npm run serve and view lead …

Add parcel lead connections

---

cdk/src/open-data-platform/data-plane/schema/schema.sql
client/src/components/MapLegend.vue
client/src/data_layer_configs/lead_and_copper_violations_by_water_system_config.ts
client/src/data_layer_configs/lead_service_lines_by_parcel_config.ts
client/src/data_layer_configs/lead_service_lines_by_water_systems_config.ts
client/src/data_layer_configs/population_by_census_block_config.ts
client/src/model/data_layer.ts
client/src/util/data_layer_util.ts

Changes the legend buckets based on zoom level. 
GeographicLevel enum which maps a geo to a zoom level upon which you see the that geo-based aggregation
LegendInfo is now a map that contains a legend for each supported geo
UI

Dynamically render legend based on zoom

---

client/.env.production
client/package-lock.json
client/package.json
client/src/components/MapGeocoderWrapper.vue
client/src/components/MapView.vue
client/tsconfig.json

Previously, the client used a Mapbox access token that each dev had in their local env variables. Since those env variables isn't available to AWS CodeBuild during deployment, this PR checks in a config file that sets them.
The access token in this file was created just for LeadOut and is restricted to `*.blueconduit.com` domains, per [the production design doc](https://docs.google.com/document/d/1zZxCoXx5JzLXTOGVdvC4s8H-r82DFjfmNU-dmFPAQVI/edit#heading=h.a5e8qo5ga0ap)
- Moved the access token to a config file.
- Some linting stuff, since the linter was complaining as I worked with this variable.
Deployed to my sandbox successfully. I checked that this new token is being used by the client in Chrome dev tools.

Brettbeekley/sc 5985/add mapbox access token to dev

---

client/src/components/GeocoderInput.vue
client/src/components/MapGeocoderWrapper.vue

I needed a geocoder for the landing page, but our existing `MapGeocoderWrapper` has map-specific code in it. I've broken out the geocoder input itself into its own component so it can be used outside of the map.
- `GeocoderInput` component
- `MapGeocoderWrapper` uses `GeocoderInput`, which emits the `lat,long` of the selected result.
There's no functional change, since this is just a refactor.

Refactor geocoder into its own component

---

api/src/geolocate/get.handler.ts
client/src/components/NationwideMap.vue
client/src/components/PredictionPanel.vue
client/src/components/ScorecardSummaryPanel.vue
client/src/model/states/model/geo_data.ts

Addresses: [story](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/9SjAy8XtQi30i0Vy55xOWx)
- Update client to fit map to provided bounding box by default (if available)
- Make geolocate/ return bounding box with geoid
- Prevent geolocate/ from swallowing failed db-query errors
- N/A
- Geolocate/ endpoint now returns a richer object including a bounding box instead of a simple string
- If multiple polygons match the provided coords, we sort by ID and return the lowest one. Previously was nondeterministic.
- The client also expects this bounding box to be passed around
- N/A
- I've only tested the one usecase I understand, which is:
- Type in an address in the home page
- Hit 'enter'
- The map should zoom into the bounding box for the zipcode. The entire zipcode should …

Make geolocate/ return bounding box with geoid

---

client/README.md
client/package.json
client/src/api/api_client.ts

https://github.com/BlueConduit/open-data-platform/pull/96 removed a hardcoded path to the API, which local development depended on. This moves it to an env variable.
Everyone should add a new line to their `.env` file that points to the API they want to use. You can check the console to see if it's using the right one. E.g.:
```
VUE_APP_API_ENDPOINT=https://beekley.leadout-sandbox.blueconduit.com
```
- `VUE_APP_API_ENDPOINT` variable for local dev. 
- API path.
My locally-built client works and makes requests to my sandbox.

Use env variable for API path.

---

api/src/geolocate/get.handler.ts
api/src/parcel/get.handler.ts

Fixes issue where a point was intersecting with multiple states, counties, etc.
Example: 
Request: /scorecard/40.716265,-73.95542 (88 Roebling St, Brooklyn NY 11211)
OLD response body (before deployment):
{"county":{"id":"36047","bounding_box":{"minLat":-74.042412,"minLon":40.5667651450013,"maxLat":-73.833041,"maxLon":40.7394}},"state":{"id":"NJ","bounding_box":{"minLat":-75.559614,"minLon":38.928519,"maxLat":-73.893628,"maxLon":41.357423}},"zip_code":{"id":"11211","bounding_box":{"minLat":-73.964849,"minLon":40.700822,"maxLat":-73.922711,"maxLon":40.725233}},"water_system_pws_id":{"id":"NY0700789","bounding_box":{"minLat":-74.258843,"minLon":40.476578,"maxLat":-73.700169,"maxLon":40.917705}}}
{"state":{"id":"NY","bounding_box":{"minLat":-79.762152,"minLon":40.496103,"maxLat":-71.856214,"m …

Change intersects to contains for more accurate API responses

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

- Previously, indexes were named, and many had conflicting names (e.g., 'geom_index').
- In conjunction with `CREATE OR REPLACE` this meant that only the first such index was created, and subsequent `CREATE INDEX` commands were ignored.
- If unspecified, Postgres will choose an index name that is typically a concatenation of the table name and the columns being indexed ( See [reference](https://www.postgresql.org/docs/current/sql-createindex.html#name) ).
- For example, `CREATE INDEX water_systems_geom_idx ON public.water_systems USING gist (geom)` will yield an index named `water_systems_geom_idx`.
- I think this should be the preferred option, UNLESS we have a usecase in which we need to reference an index by name, which  I don't think we have.
Addresses: [Fix geom index …

Fix non-existent spatial indexes by using default index names. 

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [Fix geom index issue](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/9UhD9iQW1ty6LwZTpEO4UR)
- #114 introduced a syntax error
- `IF NOT EXISTS` can only be used if creating a named entity
- This PR removes reverts to explicit naming when adding indexes and creating tables
- It uses the schema `${nameOfTable}_${nameOfColumn}_idx` to name indexes, to guarantee uniqueness
- This is identical to the default postgres naming scheme for indexes. 
- None
- Just fixed a bunch of syntax errors
- None
- Schema.sql should run now, without failing.

Fix syntax for index creation

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

- CREATE UNIQUE INDEX slipped under the radar last time since its
a UNIQUE index unlike the others.
Addresses: [Fix DB index naming](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/9UhD9iQW1ty6LwZTpEO4UR)
- Apologies. #114 still incorrectly named the zipcodes index
- This fix is definitely the last one. I checked it works by deploying and watching the logs succeed [here](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Frsrogers-OpenDataPlatform-RootSchemahandler909455B-PWnu0M0oqt3N/log-events/2022$252F08$252F20$252F$255B$2524LATEST$255D113cc4f126d14e4e9cd3bc0ec64f29c8). 
- None
- Correctly named the zipcodes index
- None
- Verify correct deployment via cloud watch logs …

Fix final naming messup

---

cdk/src/cdk.ts
cdk/src/open-data-platform/data-plane/data-plane-stack.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql
cdk/src/open-data-platform/data-plane/schema/schema.ts
cdk/src/open-data-platform/monitoring/monitoring.ts
cdk/src/open-data-platform/network/network-stack.ts
cdk/src/open-data-platform/open-data-platform.ts
cdk/src/pipeline/pipeline-stack.ts
cdk/src/util.ts
cdk/test/cdk.test.ts

Addresses: [Monitoring](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/bYcpg5d5BPEdlvjUIGh_gZ)
We currently have no monitoring. After each deployment (including to their own sandboxes), devs have to look in the logs in the AWS console to see if it succeeded.
This PR adds a chatbot and one integration to demonstrate how monitoring can work:
1. A stack defines an alert for some metric (e.g. lambda error rate).
2. The monitoring stack subscribes to an SNS topic associated with that alert.
3. The chatbot posts whenever an alert is written to that topic.
However, I don't love this CDK setup since it makes the monitoring stack dependent on all other stacks. I've had trouble updating other stacks with errors like `... cannot be deleted as it is in use by …

Add slack chatbot to notify on alerts

---

cdk/src/open-data-platform/open-data-platform.ts

There can only be one chatbot with the same config, so deployments are [failing](https://lslr.slack.com/archives/C03D5199TLG/p1661353067786629). This removes the monitoring stack to unblock `cdk deploy`.

Remove problematic stack.

---

cdk/src/open-data-platform/data-plane/schema/schema.ts
cdk/src/open-data-platform/frontend/redirect-4xx.ts
client/src/api/api_client.ts

This fixes three bugs:
* The favicon was ignored due to a CF config.
* An alarm had a conflicting name, so would not deploy if someone already deployed the same alarm.
* The API path was undefined in dev.

Fix a few deployment issues

---

client/public/index.html
client/src/util/build_id.ts
client/vue.config.js

This PR adds a log statement in the client that displays information about the current build. This allows anyone to see how recent the code is, including a link to the git commit it was built from, if present.
I considered displaying the ID somewhere in the client GUI itself, but this is faster and only visible to those who look for it. I'm open to dropping it in the corner somewhere too.
- Console log statement in the client.
I added `CODEBUILD_SOURCE_REPO_URL=testURL` to my `.env` file and see the following in my console:
We'll know for sure if the git URL works once this is deployed to dev.

Show build info in the client.

---

api/src/parcel/get.handler.ts
cdk/src/open-data-platform/data-plane/data-import/data-import-stack.ts
cdk/src/open-data-platform/data-plane/data-import/write-parcels-data.handler.ts
client/src/App.vue
client/src/api/api_client.ts
client/src/assets/messages/scorecard_messages.ts
client/src/components/LslrSection.vue
client/src/components/landing_page/ScorecardSearch.vue
client/src/model/states/model/geo_data.ts
client/src/model/states/model/lead_data.ts
client/src/router.ts
client/src/views/ScorecardView.vue

Adds LSLR section to scorecard page.
This requires adding city to the  API response and populating with the correct value on the insert lambda.
Additionally adds geoType to URL when searching from landing page. This triggers a parcel lookup when the user searches by address.
- LSLR section component
Deployed API changes and ran locally to test full stack. Tested searching both an address with a LSLR link and without to test the toggling.

Lslr section

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [Add bbox column to water_systems to decrease query execution time](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/a9-JMkJQeqe3_9Dpwnm46L)
- Because of [known postgres bugs to do with the shape of our water-systems data](https://postgis.net/docs/manual-1.3/ch05.html), out GIST indexes are being ignored in our tileserver queries, leading to slow execution times. 
- This PR 'caches' the data that *would* be stored in our GIST index in a separate 'bbox' column.
- This leads to an overall decrease in execution time from ~2.5 seconds to ~0.5 seconds for queries at zoom levels 7+.
- There are other improvements we can make, but in terms of effort-vs-reward, this is probably our highest ROI solution.
- schema.sql introduces as new stored procedure …

Use bbox col to speed up tile query exec time

---

cdk/src/pipeline.ts
cdk/src/pipeline/pipeline-stack.ts
cdk/src/util.ts

Addresses: [Dev has monitoring](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/bYcpg5d5BPEdlvjUIGh_gZ)
This PR sets up monitoring for the deployments AWS account itself. A future PR will start monitoring stuff, but that can't happen until this is merged in and the SNS topic exists.
- Deployments-monitoring pipeline stage
- light enum changes.
This successfully compiles via `npm run pipeline-synth`. But we won't know if it works until it's merged and deployed.

Add deployments-monitoring to the pipeline.

---

cdk/src/open-data-platform/app-plane/api/api-monitoring.ts
cdk/src/open-data-platform/app-plane/api/api-stack.ts
cdk/src/open-data-platform/app-plane/app-plane-stack.ts
cdk/src/pipeline/pipeline-stack.ts

Addresses: [Dev has monitoring](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/bYcpg5d5BPEdlvjUIGh_gZ)
Currently, devs have to manually check if a deployment succeeded. This PR adds a notification if the deployment pipeline failed.
I considered notifying on any changes, but that's noisy. I want to keep the signal:noise ratio high for the notifications Slack channels, which means they should only have messages if there is a problem. If it'd be useful to also notify on success, we can have another channel for that.
- Notification on pipeline failure
This successfully compiles via `npm run pipeline-synth`. But we won't know if it works until it's merged and deployed.

Alert on pipeline failure.

---

client/src/App.vue
client/src/components/NationwideMap.vue
client/src/components/PredictionPanel.vue
client/src/views/NationwideMapView.vue
client/src/views/ScorecardView.vue

Addresses: 
- Restrict pan on map. Disables drag to pan but not zoom functionality yet because we don't have accurate enough zoom for results, so we need to enable to zoom to / from parcel level for Toledo.
- Restrict parcels vue to Toledo: checks bounds of map before switching to parcel view on zoom. This will not switch back and forth between views on panning though, since there is no event to listen for this.
- Set min page width (to avoid wonky responsive views).
- Differentiates between empty state and no prediction state on scorecard. Shows 'no prediction' message when geo IDs are present but no prediction is present. If no geo IDs are present, shows message to prompt a search.
Ran locally, tested in Toledo and outside of it. Tried panning around in scorecard view. Tried responsive …

Small UI fixes

---

api/src/geolocate/get.handler.ts
client/src/api/api_client.ts
client/src/components/NationwideMap.vue
client/src/components/PredictionPanel.vue
client/src/components/ScorecardSummaryPanel.vue
client/src/data_layer_configs/lead_service_lines_by_parcel_config.ts
client/src/model/states/model/geo_data.ts

Addresses: Add toggle between zip / water system geometry
Update parcel config to read public_lead_connections_low_estimate instead of old property
Update geolocate lambda to correctly convert bounding box --> min/max lat,long. Before it was swapping lat and lng, but it worked out because the FE also was. 
Zoom tight into parcels when an address is searched and found.

Fix parcels config to use proper property to read lead + fix zooming

---

client/public/index.html

Addresses: [Switch GA to use BC's account](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/aXx97ZAfHxzdYvhNHytkk6)
This switches the Google Analytics ID to [BC's account](https://lslr.slack.com/archives/C03D8ECRC3S/p1661276665032239?thread_ts=1660938852.883329&cid=C03D8ECRC3S).
- GA ID.
My [sandbox](https://beekley.leadout-sandbox.blueconduit.com/) didn't yell at my when I deployed this. But I don't have access to the GA dashboard to test that data is flowing.

Use BC's GA account ID

---

cdk/src/open-data-platform/data-plane/schema/schema.sql

Addresses: [Complete low-hanging-fruit DB optimizations for tile serving](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/blYIQsdPnww7YU8xsoy_aD)
- Some queries fail with the error `Database returned more than the allowed response size limit`
- This PR addresses the error by filtering out smaller polygons at farther zoom levels
- This has a negligible effect on query performance
- Again, since we can't alter tables by re-running schema.sql, you'll have to run the following manually after this is merged:
```sql
ALTER TABLE public.water_systems ADD COLUMN approx_area_sq_km REAL;
UPDATE public.water_systems SET approx_area_sq_km = ST_Area(ST_Transform(geom, 4326)) / 1000000;
CREATE INDEX ON water_systems USING BTREE (approx_area_sq_km);
```
- None
- Queries at the …

Drop smaller polygons at distant zoom levels

---

client/src/components/MapGeocoderWrapper.vue
client/src/components/NationwideMap.vue

Addresses: Update scorecard page URL with geolocated address
Put lat/long in URL when user geolocates. This change affects both scorecard and map views.
tested locally using geolocate functionality and going back and forth between that and the regular geocoder component.

Geolocate fix

---

cdk/src/open-data-platform/app-plane/api/api-monitoring.ts
cdk/src/open-data-platform/app-plane/api/api-stack.ts
cdk/src/open-data-platform/app-plane/app-plane-stack.ts

https://github.com/BlueConduit/open-data-platform/pull/144 added monitoring, but didn't correctly pass the SNS Topic down the stack. This fixes that.
I missed this problem because I didn't check that the alarms actually sent anything to Slack. And the optional type still let it compile.
- Create the notification Topic from the ARN and pass it down the stack.
- Split alarms into multiple evaluation periods. This doesn't change the alarm itself, but makes the graphs more granular.
My [alarms](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#alarmsV2:alarm/beekley-OpenDataPlatformAppPlane-ApiStackAvailabilitySLOSlowBurn70D70F36-1NMZZJY6RA9A3?~(search~'beekley)) have notifications now:

Correctly notify on API monitoring

---

client/src/util/lead_data_util.ts

Fix bug introduced in https://github.com/BlueConduit/open-data-platform/pull/155/files# which removed the likelihood header when the likelihood == 0 bug.
Bug is currently visible at https://kailajeter.leadout-sandbox.blueconduit.com/scorecard/address/41.716255,-83.643702 but in the process of deploying the fix.

Fix lead connections == 0 bug.

---

client/src/components/ScorecardSummaryPanel.vue

Fix bug introduced in https://github.com/BlueConduit/open-data-platform/pull/152. Showing scorecard summary panel only when we have results means that the component is initiated after the zip field is populated. This makes it so that we need to check for zip + dispatch event to get zip demographics before the component is mounted rather than only when the zip field changes.

Fix scorecard summary panel bug.

---

cdk/src/open-data-platform/data-plane/data-import/write-parcels-data.handler.ts
client/src/components/LslrSection.vue
client/src/components/NationwideMap.vue
client/src/components/SidePanel.vue
client/src/model/states/model/geo_data.ts
client/src/util/geo_data_util.ts
client/src/views/ScorecardView.vue

Addresses: CTA#5: Display a button to sign up for an LSL replacement in pilot cities (toledo, richmond).
- Add bounding boxes for Richmond + New Orleans to intersect the lat,long with for surfacing lslr in supported cities.
- Capitalize Toledo in parcels import. (Will update dev DB when this is submitted)
- Bounding boxes + getCityForLatLong in geo data util.
- showLslrSection logic (From watcher + data variable to computed property)
Tested locally in all 3 cities, both addresses and zip codes. Tested outside of those cities too to make sure nothing shows up when there is no result.

Add support for New Orleans + Richmond to LSLR section

---

api/src/geolocate/get.handler.ts
api/src/watersystem/get.handler.ts
client/package-lock.json
client/package.json
client/src/api/api_client.ts
client/src/components/NationwideMap.vue
client/src/components/PredictionPanel.vue
client/src/components/ScorecardMapSearchBar.vue
client/src/components/SidePanel.vue
client/src/components/landing_page/ExploreMapSection.vue
client/src/components/landing_page/FilterInfoSection.vue
client/src/components/landing_page/ResourcesSection.vue
client/src/components/landing_page/SearchSection.vue
client/src/model/slices/lead_data_slice.ts
client/src/model/states/lead_data_state.ts
client/src/model/states/model/lead_data.ts
client/src/views/ScorecardView.vue
package-lock.json
package.json

Addresses: 
- Add loading indicator while the page loads data (both map and status): uses https://www.npmjs.com/package/vue-loading-overlay
- Modify API to prefer row with data (specifically water_systems, has multiple entries for some lat/longs)
- Bug with landing page Bulma implementation
Loading indicator:
This PR distinguishes water system data load status from parcel data load status in order to show the loading spinner before both sets of data return. This was causing water system data to render before parcel data in cases where there were both. 
Modify API to prefer row with data:
This sorts by # of service lines to prefer the intersecting water system which serves the largest population of people.
- Single status in leadState to water system / parcel statuses
tested locally + in …

API Fixes + Scorecard loading screen

---

client/src/assets/messages/scorecard_messages.ts
client/src/components/ActionSection.vue
client/src/components/GeoIdSection.vue
client/src/components/PredictionPanel.vue
client/src/components/ScorecardMapSearchBar.vue
client/src/components/ScorecardSummaryPanel.vue
client/src/components/ScorecardSummaryRow.vue
client/src/components/SidePanel.vue
client/src/components/landing_page/ResourcesSection.vue
client/src/views/ScorecardView.vue

Addresses: [Mobile Optimization](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/9ZLTEnkXfJeetgENepdkVs)
Like https://github.com/BlueConduit/open-data-platform/pull/153, this switches a lot of our layout CSS to use Bulma to make the scorecard responsive. 
- Pretty much all of the scorecard and its components.
- The map is hidden is mobile, leaving only the side panel.
- Refactored PredictionPanel to simplify the template.
You can play around with the UI on my sandbox: https://beekley.leadout-sandbox.blueconduit.com/

Make scorecard responsive

---

client/src/views/ScorecardView.vue

https://github.com/BlueConduit/open-data-platform/pull/157 made the loading element from https://github.com/BlueConduit/open-data-platform/pull/159 render strangely. 
This PR is a quick fix that bumps the opacity up to 100% so it hide any elements while the page loads.
- increased loading element opacity.
Set networking throttling in dev tools (e.g. mid-tier mobile) to increase the load time. Here's what it looks like on mobile

Cover the entire page with loading element until data is ready.

---

client/src/assets/messages/scorecard_messages.ts
client/src/components/ContactCitySection.vue
client/src/components/NationwideMap.vue
client/src/views/ScorecardView.vue

Addresses: CTA#2: Display contact info to call the city or water system 
Also fixes bug introduced in https://github.com/BlueConduit/open-data-platform/pull/157 which looks at the parcel city field instead of the computed property for the lslr section. 
- Contact your city section
Tested locally and in sandbox: 
[Toledo](https://kailajeter.leadout-sandbox.blueconduit.com/scorecard/address/41.724295,-83.552465) 
[New Orleans](https://kailajeter.leadout-sandbox.blueconduit.com/scorecard/postcode/29.960244,-90.073635)
[Richmond](https://kailajeter.leadout-sandbox.blueconduit.com/scorecard/postcode/37.579738,-77.53986)

Call city implementation

---

client/src/components/ResponsiveNav.vue

Addresses: [Remove resources link in navbar.](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/aubWVjT8XO_0CiSUtKW_Rz)
The resources page doesn't have much right now, so we shouldn't be advertising it. This keeps any other links, such as from the scorecard.
- Link in navbar.
Local testing.

Remove resources link in navbar.

---

cdk/src/open-data-platform/data-plane/data-import/handler-factory.ts
cdk/src/open-data-platform/data-plane/data-import/write-water-systems-data.handler.ts

- From adding some timestamps (preserved in this PR) and inspecting the logs it appears that each insertion operation takes around 10 seconds, irrespective of whether we're inserting [10 rows](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Frsrogers-OpenDataPlatform-DataImportStackwritewate-bnHStk6DBLka/log-events/2022$252F09$252F12$252F$255B$2524LATEST$255Dfa1a1c00f74345a0bd17975e438e2473) or [1000 rows](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Frsrogers-OpenDataPlatform-DataImportStackwritewate-bnHStk6DBLka/log-events/2022$252F09$252F12$252F$255B$2524LATEST$255Dca5b79ca729d4b8aa022021f0f0dd40b). 
- It therefore makes sense to …

Make water-systems-imports a bit faster and more reliable

---

client/src/components/GeoIdSection.vue
client/src/views/ScorecardView.vue

When making the scorecard responsive, the side panel got a dynamic-width, which looks weird on a side screen.
This PR fixes the width.
- Side panel has a max-width.
- GeoIdSections have a dynamic width to fill the side panel. Consequently, they are now wider in the mobile view when not constrained next to the map.
Locally tested at different screen sizes.
Mobile:
Tablet:
Desktop:

Fix side panel width

---

client/src/components/scorecard_page/ScorecardSummaryPanel.vue

Addresses: Investigate whether low or high income index mean higher income (get clarity and update content for this)
Lower percentiles are lower income. Updated copy to reflect that.

Switch income percentiles for scorecard summary

---

client/src/assets/messages/scorecard_messages.ts
client/src/components/scorecard_page/ScorecardSummaryPanel.vue
client/src/components/scorecard_page/ScorecardSummaryRow.vue
client/src/views/ScorecardView.vue

Addresses: Reorder scorecard sections based on user testing feedback
"Moves Understanding your Statu " above "Here's what you can do" in accordance with new [mocks](https://www.figma.com/file/0LGxjZnPD3N0dCqHv8LRr6/NW-Map-Design-System-WIP?node-id=1057%3A6040) / user feedback
Copy inside these sections to reflect new text
Removed double "Actions to take" section

Reorder sections based on user feedback

---

cdk/src/monitoring/synthetics.handler.js
cdk/src/monitoring/synthetics.handler.ts
cdk/src/monitoring/synthetics.ts

Addresses: [Canaries](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/826xIGWGqdF62fj6Icp__4)
The canaries started failing after https://github.com/BlueConduit/open-data-platform/pull/186 changed a string. Since the canary handler is a single JS blob, this PR does some string manipulation to combine the handler with the messages file so that the handler can reference the same `ScorecardMessages` as the client.
- Semi-hacky transpiling method of importing the handler.
- Replaced strings in the handler with references to `ScorecardMessages` properties.
The [canaries](https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#synthetics:canary/detail/monitoringsynth81c9cc) pass in my sandbox!

Use common messages file in the canaries

---

client/src/assets/messages/landing.ts
client/src/router.ts
client/src/views/ThankYouView.vue

Addresses: Adds thank you page to be routed to after users subscribe to LeadOut.
Right now there is no entrypoint to this page in the app - this will be hooked up to the hubspot form in the editor.
- ThankYouView component.
ran locally and routed to http://localhost:8080/subscribed 
[screenshot](https://screenshot.googleplex.com/9wKpnED7MoYbayi)

Thank you page finished.

---

.github/workflows/unit-test.yaml
cdk/src/pipeline/pipeline-stack.ts

https://github.com/BlueConduit/open-data-platform/pull/195 broke the pipeline with:
> Error: There is already a Construct with name 'Dev' in PipelineStack [OpenDataPlatformPipeline]
This PR gives the monitoring stacks a unique name.
`npm run pipeline-synth` succeeds. I forgot to test that before, so I added it as a pre-merge action too. This would have caught the bug, since this command currently fails on `main`.
But we won't really know until the pipeline runs.

Name monitoring stages uniquely.

---

cdk/src/open-data-platform/data-plane/data-import/write-violations-data.handler.ts
cdk/src/open-data-platform/data-plane/schema/schema.sql

Remove county from violation_counts view and add population of state census geo id to violations handler.
Tested in sandbox: https://kailajeter.leadout-sandbox.blueconduit.com/map?layer=epa-lead-and-copper-violations-by-water-system

Geoid in violations

---

README.md
docs/operational-playbook.md
docs/writing-tests.md

Addresses: [Document how to add a unit or integration test](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/boG3sZPFRyPat4NLJcK_u8)
This adds a few brief guides on how we wrote tests.
You can see it rendered [here](https://github.com/BlueConduit/open-data-platform/blob/docs/test/docs/writing-tests.md).

Document how to add a unit or integration test

---

cdk/src/pipeline/pipeline-stack.ts

Addresses: [prod release bug](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/aYULtWDiYqJ3UfnBL1M4P0)
Prod was failing to deploy with the following:
```
[Container] 2022/10/05 17:46:11 Running command if [[ $( aws cloudwatch describe-alarms --query 'MetricAlarms[?contains(AlarmName, `Dev-OpenDataPlatform`) == `true` && StateValue!=`OK` && !contains(AlarmName, `TargetTracking`)]' --output text) ]]; then exit 1; fi
An error occurred (AccessDenied) when calling the DescribeAlarms operation: User: arn:aws:sts::223904267317:assumed-role/OpenDataPlatformPipeline-PipelineProdBakeStepRole3-TQJ1E0VEFJO2/AWSCodeBuild-c3276479-c035-4255-b25a-f1e5b0630906 is not authorized to perform: cloudwatch:DescribeAlarms on resource: arn:aws:cloudwatch:us-east-2:223904267317:alarm:* because …
```

Cut much of the bake steps from the release pipeline.

---

cdk/src/pipeline/pipeline-stack.ts

Addresses: [prod release bug](https://tables.area120.google.com/table/bX_kMNBW8LA35n6l5Hz_co/row/aYULtWDiYqJ3UfnBL1M4P0)
https://github.com/BlueConduit/open-data-platform/pull/218 Tried to address some pipeline problems. But it's still timing out because CodeBuild has a 1h timeout.
- Reduce bake to <1h
We'll have to see in the pipeline...

Reduce bake to <1h

---

client/src/assets/blog/blog_post.ts
client/src/assets/blog/history_of_lead.ts
client/src/assets/blog/next_steps.ts
client/src/assets/blog/understand_lead_status.ts
client/src/router.ts
client/src/views/BlogView.vue

Addresses: 
Blog posts about (1) the history of lead (2) understanding lead status. They are not yet linked.
Made BlogPost interface so it's extendable
[history](https://screenshot.googleplex.com/5CJ4gAaCfjEz3Lz)
[understanding](https://screenshot.googleplex.com/9hKaxSfxpKCgJQk)

History of lead blog post

---

cdk/cdk.context.json
cdk/src/open-data-platform/network/network-stack.ts

Addresses: [Deploy Leadout & Load Data in Dev Env](https://app.shortcut.com/blueconduit/story/6966/deploy-leadout-load-data-in-development-environment)
Currently we do a conditional lookup for an existing VPC resource when:
- deploying to `Development` via pipeline
- deploying to sandbox via `cdk deploy --all`
This lookup is done via a brittle hardcoded `vpcId`. Instead, this PR creates a fresh VPC in all deployment scenarios.
In the future, we may follow an internal pattern (established in `tributary`) to share the same VPC resource between dev sandboxes. This would be desirable because VPC resources are monetarily expensive - having one per dev is a bit cost inefficient. Holding off, though, until we have more clarity on development & maintenance expectations for this repo.
- Ran `cdk …

feat(cdk): make VPC creation env-independent

---

cdk/src/open-data-platform/frontend/frontend-stack.ts
cdk/src/pipeline/pipeline-stack.ts
client/public/index.html

Addresses: [Please Noindex Leadout.blueconduit.com for now](https://app.shortcut.com/blueconduit/story/7327/please-noindex-leadout-blueconduit-com-for-now)
- Add ```noindex,nofollow``` meta tag to prevent leadout from being indexed by search engines until it's ready
- Redirect HTTP -> HTTPS through cloudfront
- Replace bake time with manual approval before promoting to Prod to facilitate faster iteration during development
We don't have sandbox envs setup for leadout and thanks to an ops event brought to you by EPIC, we'll test in the pipeline.

feat: redirect to https and set noindex,nofollow

---

cdk/src/open-data-platform/frontend/frontend-stack.ts

Redirect the leadout.blueconduit.com subdomain to a "coming soon" page on the BC marketing website. LeadOut is not ready to be launched to the public yet so this change is in response to learning that EPIC is planning on releasing a blog post linking to leadout.blueconduit.com in a day.
_Short, descriptive summary of the changes_
After deploying to the dev environment, go to leadout-dev.blueconduit.com and verify that you get redirected to the right page on the BC marketing website.

network: top level redirect to blueconduit.com/lsl-solutions/nationwide-map/
